---
title: "FIGI Post-harmonization"
bibliography: /home/rak/Dropbox/library.bib
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    theme: "united"
params:
  exposure: "asp_ref"
  is_exposure_categorical: TRUE
  energy_adj: TRUE
  covariates_suffix: "age_ref_imp_sex_energytot_imp_study_gxe_pc1_pc2_pc3" # so far only thing that uses this is qq + manhattan plots (names)
---

<!-- Comments -->
<!-- the easiest way to mass produce is to assume that covariates for meta-analyses and stratified analyses remain the same across all exposures..  -->
<!-- Looks like I have to create a separate rmd document for each exposure after all  -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, error = F)
```


<style type="text/css">
.main-container {
  max-width: 1800px !important;
  margin-left: auto;
  margin-right: auto;
}

table, td, th {
  border: none;
  padding-left: 1em;
  padding-right: 1em;
  margin-top: 1em;
  margin-bottom: 1em;
}

</style>


```{r package_setup, include = F}
library(tidyverse)
library(data.table)
library(ggplot2)
library(qqman)
library(table1)
library(meta)
library(rlang)
library(broom)
library(effects)
library(figifs)
library(DT)
library(grid)
library(sjPlot)
library(stargazer)
library(nnet)
library(forcats)
```


<!-- IMPORTANT - Descriptive information is the only section that uses an exposure specific child Rmd document -->
<!-- # Descriptive analysis -->
<!-- ```{r child = paste0(params$exposure, "/results_report_child_descriptive_analysis.Rmd")} -->
<!-- ``` -->


<!-- # Investigate exclusion/inclusion of prevalent cases -->

<!-- <br><br> -->

<!-- | Study | GxE_Case | Prevalent | Incident | -->
<!-- |--------------|----------|-----------|----------| -->
<!-- | ASTERISK | 892 | 696 | 196 | -->
<!-- | ATBC | 152 | 0 | 152 | -->
<!-- | BWHS | 179 | 0 | 179 | -->
<!-- | CCFR | 3211 | 315 | 2896 | -->
<!-- | CLUEII | 272 | 0 | 272 | -->
<!-- | Colo2&3 | 87 | 32 | 55 | -->
<!-- | ColoCare | 301 | 0 | 301 | -->
<!-- | COLON | 648 | 0 | 648 | -->
<!-- | CORSA | 2715 | 1179 | 1536 | -->
<!-- | CPSII | 888 | 0 | 888 | -->
<!-- | CRCGEN | 893 | 0 | 893 | -->
<!-- | CzechCCS | 1681 | 0 | 1681 | -->
<!-- | DACHS | 4528 | 0 | 4528 | -->
<!-- | DALS | 1099 | 0 | 1099 | -->
<!-- | EDRN | 299 | 0 | 299 | -->
<!-- | EPIC | 2027 | 0 | 2027 | -->
<!-- | EPICOLON | 275 | 0 | 275 | -->
<!-- | ESTHER_VERDI | 418 | 0 | 418 | -->
<!-- | GALEON | 92 | 0 | 92 | -->
<!-- | HawaiiCCS | 163 | 22 | 141 | -->
<!-- | HPFS | 858 | 0 | 858 | -->
<!-- | Kentucky | 961 | 47 | 914 | -->
<!-- | LCCS | 1412 | 444 | 968 | -->
<!-- | MCCS | 754 | 1 | 753 | -->
<!-- | MEC | 709 | 0 | 709 | -->
<!-- | MECC | 5217 | 1663 | 3554 | -->
<!-- | MOFFITT | 412 | 282 | 130 | -->
<!-- | NCCCSI | 433 | 0 | 433 | -->
<!-- | NCCCSII | 766 | 0 | 766 | -->
<!-- | NFCCR | 627 | 167 | 460 | -->
<!-- | NGCCS | 1117 | 0 | 1117 | -->
<!-- | NHS | 1443 | 0 | 1443 | -->
<!-- | NSHDS | 409 | 0 | 409 | -->
<!-- | PHS | 374 | 9 | 365 | -->
<!-- | PLCO | 2959 | 0 | 2959 | -->
<!-- | PPS3 | 80 | 0 | 80 | -->
<!-- | PPS4 | 168 | 0 | 168 | -->
<!-- | REACH | 89 | 0 | 89 | -->
<!-- | SEARCH | 4270 | 0 | 4270 | -->
<!-- | SELECT | 303 | 0 | 303 | -->
<!-- | SMC_COSM | 579 | 41 | 538 | -->
<!-- | SMS | 46 | 0 | 46 | -->
<!-- | UKB | 2996 | 0 | 2996 | -->
<!-- | USC_HRT_CRC | 440 | 0 | 440 | -->
<!-- | VITAL | 270 | 0 | 270 | -->
<!-- | WHI | 1986 | 0 | 1986 | -->
<!-- | Total | 50498 | 4898 | 45600 | -->

<!-- <br><br> -->



# Exposure main effects

```{r data_setup, include = F}

format_data_desc <- function(d, exposure, is_e_categorical, min_cell_size = 0) {

  # note that in gxe set, outcome+age_ref_imp+sex+study_gxe+energytot_imp do NOT have missing values
  # OK to subset simply by using is.na(exposure)
  tmp <- d %>%
    dplyr::filter(gxe == 1,
                  !is.na(get(exposure))) %>%
    dplyr::mutate(outcome = ifelse(outcome == "Control", 0, 1),
                  sex = ifelse(sex == "Female", 0, 1))
  
  # drop zero cells, keep vars_to_keep
  if (is_e_categorical == T) {
    tmp <- mutate(tmp, {{exposure}} := as.numeric(get(exposure)) - 1)
    
    drops <- data.frame(table(tmp$outcome, tmp[, exposure], tmp$study_gxe)) %>%
      filter(Freq <= min_cell_size)
    
    tmp <- filter(tmp, !study_gxe %in% unique(drops$Var3)) %>%
      dplyr::mutate(study_gxe = fct_drop(study_gxe)) }
  else {
    drops <- data.frame(table(tmp$outcome, tmp$study_gxe)) %>%
      filter(Freq <= min_cell_size)
    tmp <- filter(tmp, !study_gxe %in% unique(drops$Var2)) %>%
      dplyr::mutate(study_gxe = fct_drop(study_gxe))  }
  
  return(tmp)
  
}


figi_gwas <- readRDS("~/data/FIGI_EpiData_rdata/FIGI_HRC_v2.3_GWAS.rds")
gxe <- format_data_desc(figi_gwas, params$exposure, params$is_exposure_categorical, 0)
```

## Meta-Analysis {.tabset}
```{r child = 'results_report_child_meta_analysis.Rmd'}
```

## Heterogeneity in pooled analysis {.tabset}
```{r child = 'results_report_child_pooled_analysis.Rmd'}
```

<!-- # QQ + Manhattan Plots {.tabset} -->
<!-- ```{r child = 'results_report_child_qq_manhattan.Rmd' } -->
<!-- ``` -->


