---
title: "FIGI NSAID aspirin postharmonization"
bibliography: /home/rak/Dropbox/library.bib
output: 
  #pdf_document:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    theme: "united"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style type="text/css">
.main-container {
  max-width: 1800px !important;
  margin-left: auto;
  margin-right: auto;
}
</style>


```{r package_setup, include = F}
library(tidyverse)
library(data.table)
library(ggplot2)
library(qqman)
library(table1)
library(rmeta)
library(rlang)
library(broom)
source("/home/rak/Dropbox/FIGI/Code/Functions/FIGI_PostHarmonization_Functions.R")
```


```{r data_setup, include = F}
pca <- "/home/rak/data/PCA/190506/FIGI_GxESet_KGP_pc20_190430.eigenvec"
load("~/data/FIGI_EpiData_rdata/FIGI_Genotype_Epi_190424.RData")

# slightly different from epiData scripts
# keep it minimal: 
# - filter drop/gxe
# - only fix outcome, E, and 'colo2&3' study_gxe name
# leave everything else to the functions
pc30k <- fread(pca, skip = 1, 
               col.names = c("FID", "IID", paste0(rep("PC", 20), seq(1,20))))
cov <- figi %>%
  filter(drop == 0 & gxe == 1) %>% 
  inner_join(pc30k, by = c('vcfid' = 'IID')) %>% 
  mutate(outcome = ifelse(outc == "Case", 1, 0),
         age_ref_imp = as.numeric(age_ref_imp),
         sex = ifelse(sex == "Female", 0, 1),
         study_gxe = ifelse(study_gxe == "Colo2&3", "Colo23", study_gxe),
         aspirin = ifelse(aspirin == "Yes", 1, ifelse(asp_ref == "No", 0, NA)))

# filter is.na(aspirin), but not other variables
# catVars <- c("outcome", "aspirin", "sex", "study_gxe")
# df <- cov %>% 
#   filter(!is.na(aspirin)) %>% 
#   mutate(outcome_table1 = factor(outcome, levels = c(0,1,2), labels=c("Control", "Treatment", "P-value"))) %>% 
#   mutate_at(., catVars, as.factor)
# 
# drops <- data.frame(table(df$study_gxe, df$outcome)) %>% 
#   filter(Freq == 0)
# exclude_studies <- as.vector(unique(drops$Var1))
# 
# df <- filter(df, !(study_gxe %in% exclude_studies))

```


# BoxPlots {.tabset}
```{r, echo = F, message = F, cache = T, fig.height=16, fig.width=13}
createBarPlot(cov, outcome, aspirin, c(NA, 0, 1), c("NA", "No", "Yes"), c( "black", "cyan", "red"))

```
<br><br><br>


# Tables {.tabset}

## Overall
```{r, echo = F, message = F, cache = T}
createTable1(cov, outcome, aspirin, c("sex", "age_ref_imp"), c("sex"))
```
<br><br><br>

## cancer_site_sum1 = 'colon'
```{r, echo = F, message = F, cache = T}
createTable1(cov %>% filter(cancer_site_sum1 == "colon" | outcome == 0), outcome, aspirin, c("sex", "age_ref_imp"), c("sex"))
```
<br><br><br>

## cancer_site_sum1 = 'rectal'
```{r, echo = F, message = F, cache = T}
createTable1(cov %>% filter(cancer_site_sum1 == "rectal" | outcome == 0), outcome, aspirin, c("sex", "age_ref_imp"), c("sex"))
```
<br><br><br>




# Meta Analyses {.tabset}

## All tumor sites
```{r, echo = F, message = F, cache = T, fig.height=13, fig.width=13}
x <- getCounts_byOutcome(cov, outcome, aspirin)
y <- getGLM_byGroup(cov, outcome, aspirin, c("age_ref_imp", "sex"))
run_meta_analysis_create_forestplot(x, y, "aspirin use @ ref time \nModel: outcome~aspirin+age_ref_imp+sex") 
```
<br><br><br>

## cancer_site_sum1 = 'colon'
```{r, echo = F, message = F, cache = T, fig.height=13, fig.width=13}
tmp <- cov %>% filter(cancer_site_sum1 == "colon" | outcome == 0)

x <- getCounts_byOutcome(tmp, outcome, aspirin)
y <- getGLM_byGroup(tmp, outcome, aspirin, c("age_ref_imp", "sex"))
run_meta_analysis_create_forestplot(x, y, "aspirin use @ ref time \nModel: outcome~aspirin+age_ref_imp+sex")
```
<br><br><br>

## cancer_site_sum1 = 'rectal'
```{r, echo = F, message = F, cache = T, fig.height=13, fig.width=13}
tmp <- cov %>% filter(cancer_site_sum1 == "rectal" | outcome == 0)

x <- getCounts_byOutcome(tmp, outcome, aspirin)
y <- getGLM_byGroup(tmp, outcome, aspirin, c("age_ref_imp", "sex"))
run_meta_analysis_create_forestplot(x, y, "aspirin use @ ref time \nModel: outcome~aspirin+age_ref_imp+sex")
```
<br><br><br>