---
title: "scratch paper"
output: 
  #pdf_document:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(broom)
library(table1)
library(kableExtra)
library(data.table)
library(rlang)
library(rmeta)
library(qqman)
library(stargazer)
```


<!-- # Table1 -->
<!-- ```{r tableone, message=F, echo=F, warning=F, tidy=T, cache=T} -->

<!-- cov <- readRDS("~/data/GxEScanR_PhenotypeFiles/FIGI_GxESet_asp_ref_sex_age_pc10_studygxe_72145_GLM.rds") -->

<!-- numeric_vars <- c("age_ref_imp") -->

<!-- df <- cov %>% -->
<!--   mutate_at(numeric_vars, as.numeric) %>% -->
<!--   mutate(outcome = factor(outcome, labels = c("Control", "Case")), -->
<!--          asp_ref = factor(asp_ref, labels = c("No", "Yes")), -->
<!--          sex = factor(sex, labels = c('Female', 'Male'))) -->

<!-- label(df$age_ref_imp) <- "Age" -->
<!-- label(df$sex) <- "Sex" -->
<!-- label(df$asp_ref) <- "Regular Aspirin/NSAID use" -->

<!-- my.render.cont <- function(x) { -->
<!--   with(stats.apply.rounding(stats.default(x), digits=2), -->
<!--        c("", "Mean (SD)"=sprintf("%s (&plusmn; %s)", MEAN, SD))) -->
<!-- } -->
<!-- my.render.cat <- function(x) { -->
<!--   c("", sapply(stats.default(x), -->
<!--                function(y) with(y, sprintf("%d (%0.0f %%)", FREQ, PCT)))) -->
<!-- } -->

<!-- table1(~ age_ref_imp + sex + asp_ref | outcome , -->
<!--        data=df, -->
<!--        render.continuous=my.render.cont, -->
<!--        render.categorical=my.render.cat) -->

<!-- ``` -->
<!-- <br> -->


<!-- # previous hits in asp_ref GWIS -->
<!-- ```{r annotation_list, message=F, echo=F, warning=F, tidy=T, cache=T} -->
<!-- results <- readRDS("rds/marginal_g_previoushits_replicates2.rds")      -->
<!-- library(kableExtra) -->
<!-- kable(results[1:17,], format = 'html') %>% -->
<!--   kable_styling(bootstrap_options = c("condensed"), full_width = F, position = "left") -->
<!-- ``` -->
<!-- <br> -->


<!-- ```{r annotation_list2, message=F, echo=F, warning=F, tidy=T, cache=T} -->
<!-- results <- readRDS("rds/marginal_g_previoushits_replicates2.rds")      -->
<!-- library(kableExtra) -->
<!-- kable(results[18:33,], format = 'html') %>% -->
<!--   kable_styling(bootstrap_options = c("condensed"), full_width = F, position = "left") -->
<!-- ``` -->
<!-- <br> -->


<!-- # Meta-Regression -->
<!-- ```{r meta_regression, message=F, echo=F, warning=F, tidy=F, results = 'asis', cache=T} -->
<!-- source("~/Dropbox/FIGI/code/Functions/postharmonization_GWISresults_useful_functions.R") -->
<!-- cov <- readRDS("~/data/GxEScanR_PhenotypeFiles/FIGI_GxESet_asp_ref_sex_age_pc10_studygxe_72145_GLM.rds") -->
<!-- names(cov); table(cov$study_gxe) -->

<!-- # by study design -->
<!-- studylist <- sort(unique(cov$study_gxe)) -->
<!-- casecontrol <- studylist[c(2:4,6,9:15,20,25:30,42,44,46)] -->
<!-- cohort <- studylist[!studylist %in% casecontrol] -->

<!-- model <- glm_by_group_df(data = cov, group = study_gxe, exposure = asp_ref, outcome = outcome, age_ref_imp, sex) %>%  -->
<!--   mutate(study_design = ifelse(study_gxe %in% cohort, 0, 1)) -->
<!-- inv_var_weight <- model$std.error^2 -->
<!-- model_meta <- lm(estimate ~ study_design, data = model, weights = inv_var_weight) -->
<!-- summary(model_meta) -->
<!-- stargazer(model_meta, type = 'html', title = "Study Design", single.row = T) -->


<!-- # by study country (america vs non_american) -->
<!-- studylist <- sort(unique(cov$study_gxe)) -->
<!-- american <- studylist[c(2:8,13:20,23:24,28:44,46:50)] -->
<!-- nonamerican <- studylist[!studylist %in% american] -->

<!-- model <- glm_by_group_df(data = cov, group = study_gxe, exposure = asp_ref, outcome = outcome, age_ref_imp, sex) %>%  -->
<!--   mutate(american_nonAmerican = ifelse(study_gxe %in% american, 0, 1)) -->
<!-- inv_var_weight <- model$std.error^2 -->
<!-- model_meta <- lm(estimate ~ american_nonAmerican, data = model, weights = inv_var_weight) -->
<!-- summary(model_meta) -->
<!-- stargazer(model_meta, type = 'html', title = "Study Country (American vs Non-American)", single.row = T) -->


<!-- ``` -->





# Distribution of E by various components..
<!-- table1 is nice for publication ready summary tables, but not for navigating values etc -->
```{r test1, message=F, echo=F, warning=F, tidy=T, cache=T}

# 
df <- readRDS("rds/counts_asp_ref.rds") %>% 
  dplyr::select(study_gxe, Case_No, Case_Yes, Case_, Control_No, Control_Yes, Control_)

sketch = htmltools::withTags(table(
  class = 'display',
  thead(
    tr(
      th(rowspan = 2, 'study_gxe'),
      th(colspan = 3, 'Cases'),
      th(colspan = 3, 'Controls')
    ),
    tr(
      lapply(rep(c('No', 'Yes', 'NA'), 2), th)
    )
  )
))

library(DT)
library(htmltools)
datatable(df, rownames = F,  container = sketch, caption = "asp_ref counts by study/outcome - n (%)")
```
<br>


