---
title: "FIGI Post-harmonization"
bibliography: /home/rak/Dropbox/library.bib
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    theme: "united"
params:
  exposure: "asp_ref"
  covariates: "age_ref_imp_sex_study_gxe_pc1_pc2_pc3" # so far only thing that uses this is qq + manhattan plots (names)
---

<!-- Comments -->
<!-- the easiest way to mass produce is to assume that covariates for meta-analyses and stratified analyses remain the same across all exposures..  -->
<!-- Looks like I have to create a separate rmd document for each exposure after all  -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, error = F)
```


<style type="text/css">
.main-container {
  max-width: 1800px !important;
  margin-left: auto;
  margin-right: auto;
}

table, td, th {
  border: none;
  padding-left: 1em;
  padding-right: 1em;
  margin-top: 1em;
  margin-bottom: 1em;
}

</style>


```{r package_setup, include = F}
library(tidyverse)
library(data.table)
library(ggplot2)
library(qqman)
library(table1)
library(meta)
library(rlang)
library(broom)
library(effects)
library(figifs)
library(DT)
library(grid)
library(sjPlot)
library(stargazer)
library(nnet)
library(forcats)
```

<!-- IMPORTANT - Descriptive information is the only section that uses an exposure specific child Rmd document -->
# Descriptive analysis
```{r child = paste0(params$exposure, "/results_report_child_descriptive_analysis.Rmd")}
```



# Exposure main effects

```{r data_setup, include = F}
data <- readRDS(paste0("~/data/GxEScanR_PhenotypeFiles/FIGI_gxeset_", params$exposure, "_", params$covariates, "_full.rds"))
```

## Meta-Analysis {.tabset}
```{r child = 'results_report_child_meta_analysis.Rmd'}
```

## Heterogeneity in pooled analysis {.tabset}
```{r child = 'results_report_child_pooled_analysis.Rmd'}
```

<!-- # QQ + Manhattan Plots {.tabset} -->
<!-- ```{r child = 'results_report_child_qq_manhattan.Rmd' } -->
<!-- ``` -->


