---
title: "FIGI GxE"
bibliography: /home/rak/Dropbox/library.bib
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    theme: "united"
params:
  exposure: "asp_ref"
  is_exposure_categorical: TRUE
  energy_adj: TRUE
  covariates_suffix: "age_ref_imp_sex_energytot_imp_study_gxe_pc1_pc2_pc3" # so far only thing that uses this is qq + manhattan plots (names)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, error = F)
```

<style type="text/css">
.main-container {
  max-width: 1800px !important;
  margin-left: auto;
  margin-right: auto;
}

table, td, th {
  border: none;
  padding-left: 1em;
  padding-right: 1em;
  margin-top: 1em;
  margin-bottom: 1em;
}

</style>


```{r package_setup, include = F}
library(tidyverse)
library(data.table)
library(ggplot2)
library(qqman)
library(table1)
library(meta)
library(rlang)
library(broom)
library(effects)
library(figifs)
library(DT)
library(grid)
library(sjPlot)
library(stargazer)
library(nnet)
library(forcats)
```


```{r data_setup, include = F}
# use glm/gxescanr phenotype files to create subsets for descriptive, meta, and pooled analyses
# (to ensure same subset of individuals as gxescanr runs)
figi_gwas <- readRDS("~/data/FIGI_EpiData_rdata/FIGI_HRC_v2.3_GWAS.rds") 
exposure_subset <- readRDS(paste0("~/data/GxEScanR_PhenotypeFiles/FIGI_v2.3_gxeset_", params$exposure, "_basic_covars_glm.rds"))$vcfid

# data for meta and pooled analysis
gxe <- figi_gwas %>% 
  dplyr::filter(vcfid %in% exposure_subset) %>%
  dplyr::mutate(outcome = ifelse(outcome == "Control", 0, 1),
                sex = ifelse(sex == "Female", 0, 1))
gxe[,params$exposure] <- (as.numeric(gxe[, params$exposure]) - 1)

# data for descriptive stats
gxe_table1 <- figi_gwas %>% 
  dplyr::filter(vcfid %in% exposure_subset)

label(gxe_table1$outcome) <- "Outcome"
label(gxe_table1$sex) <- "Sex"
label(gxe_table1$age_ref_imp) <- "Age"
label(gxe_table1$bmi) <- "BMI"
label(gxe_table1$heightcm) <- "Height"
label(gxe_table1$famhx1) <- "Family History of CRC"
label(gxe_table1$educ) <- "Education (highest completed)"
label(gxe_table1$smoke) <- "Smoking Status"

label(gxe_table1$alcoholc) <- "Alcohol Intake"
label(gxe_table1$hrt_ref_pm) <- "Any Post-Menopausal HRT Use"
label(gxe_table1$diab) <- "T2D (ever diagnosed)"
label(gxe_table1$calcium_totqc2) <- "Total Calcium Intake"
label(gxe_table1$folate_totqc2) <- "Total Folate Intake"
label(gxe_table1$fiberqc2) <- "Total Fiber Intake"
label(gxe_table1$redmeatqc2) <- "Total Red Meat Intake"
label(gxe_table1$procmeatqc2) <- "Total Processed Meat Intake"
label(gxe_table1$fruitqc2) <- "Total Fruit Intake"
label(gxe_table1$vegetableqc2) <- "Total Vegetable Intake"

units(gxe_table1$heightcm) <- "cm"
```


<!-- IMPORTANT - Exposure specific script -->
# Descriptive
```{r child = paste0("results_report_child_descriptive_analysis_", params$exposure, ".Rmd")}
```

# Meta-Analysis {.tabset}
```{r child = 'results_report_child_meta_analysis.Rmd'}
```

# Heterogeneity in pooled analysis {.tabset}
```{r child = 'results_report_child_pooled_analysis.Rmd'}
```

<!-- # QQ + Manhattan Plots {.tabset} -->
<!-- ```{r child = 'results_report_child_qq_manhattan.Rmd' } -->
<!-- ``` -->


