---
title: "FIGI GWIS Results"
bibliography: /home/rak/Dropbox/library.bib
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    theme: "united"
params:
  exposure: "asp_ref"
  is_exposure_categorical: TRUE
  energy_adj: FALSE
  table1_by_e: FALSE
  covariates_suffix: "age_ref_imp_sex_study_gxe_pc1_pc2_pc3" # so far only thing that uses this is qq + manhattan plots (names)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, error = F)
```

<style type="text/css">
.main-container {
  max-width: 1800px !important;
  margin-left: auto;
  margin-right: auto;
}

table, td, th {
  border: none;
  padding-left: 1em;
  padding-right: 1em;
  margin-top: 1em;
  margin-bottom: 1em;
}

/* Whole document: */
body{
  font-family: Helvetica;
  font-size: 14pt;
}
/* Headers */
/* h1,h2,h3,h4,h5,h6{ */
/*  font-size: 24pt; */
}



</style>


```{r package_setup, include = F}
library(tidyverse)
library(data.table)
library(ggplot2)
library(qqman)
library(table1)
library(meta)
library(rlang)
library(broom)
library(effects)
library(figifs)
library(DT)
library(grid)
library(sjPlot)
library(stargazer)
library(nnet)
library(forcats)
library(kableExtra)
```



```{r data_setup, include = F}
# use glm/gxescanr phenotype files to create subsets for descriptive, meta, and pooled analyses
# (to ensure same subset of individuals as gxescanr runs)
figi_gwas <- readRDS("~/data/FIGI_EpiData_rdata/FIGI_HRC_v2.3_GWAS.rds")
exposure_subset <- readRDS(paste0("~/data/GxEScanR_PhenotypeFiles/FIGI_v2.3_gxeset_", params$exposure, "_basic_covars_glm.rds"))$vcfid

# data for meta-analysis and pooled analysis
gxe <- figi_gwas %>%
  dplyr::filter(vcfid %in% exposure_subset) %>%
  dplyr::mutate(outcome = ifelse(outcome == "Control", 0, 1),
                sex = ifelse(sex == "Female", 0, 1))

if(params$is_exposure_categorical == T) {
  gxe[,params$exposure] <- (as.numeric(gxe[, params$exposure]) - 1) # this is only applicable for categorical variables 
}

# data for descriptive statistics table
# (add exposures here as you create the reports)


## (also, if you're using analytical subset, there shouldn't be NA factor level)
## keep this as old version if you need to go back to it
# gxe_table1 <- figi_gwas %>%
#   dplyr::filter(vcfid %in% exposure_subset) %>% 
#   dplyr::mutate(outcome = droplevels.factor(outcome), 
#                 table1_asp_ref = factor(asp_ref, exclude = NA, levels = c("No", "Yes", "P-value")),
#                 asp_ref = fct_explicit_na(asp_ref, na_level = "NA"), 
#                 asp_ref = fct_relevel(asp_ref, "No", "Yes", "NA"))

gxe_table1 <- figi_gwas %>%
  dplyr::filter(vcfid %in% exposure_subset) %>%
  dplyr::mutate(outcome = droplevels.factor(outcome),
                table1_asp_ref = factor(asp_ref, exclude = NA, levels = c("No", "Yes", "P-value")),
                asp_ref = fct_relevel(asp_ref, "No", "Yes"),
                table1_aspirin = factor(aspirin, exclude = NA, levels = c("No", "Yes", "P-value")),
                aspirin = fct_relevel(aspirin, "No", "Yes"),
                table1_nsaids = factor(nsaids, exclude = NA, levels = c("No", "Yes", "P-value")),
                nsaids = fct_relevel(nsaids, "No", "Yes"),
                table1_folate_totqc2 = factor(folate_totqc2, exclude = NA, levels = c("1", "2", "3", "4", "P-value")),
                folate_totqc2 = fct_relevel(folate_totqc2, "1", "2", "3", "4"),
                table1_folate_dietqc2 = factor(folate_dietqc2, exclude = NA, levels = c("1", "2", "3", "4", "P-value")),
                folate_dietqc2 = fct_relevel(folate_dietqc2, "1", "2", "3", "4"),
                table1_alcoholc_heavy = factor(alcoholc_heavy, exclude = NA, levels = c("nondrinker", ">28g/d", "P-value")),
                alcoholc_heavy = fct_relevel(alcoholc_heavy, "nondrinker", ">28g/d"),
                table1_alcoholc_moderate = factor(alcoholc_moderate, exclude = NA, levels = c("nondrinker", "1-28g/d", "P-value")),
                alcoholc_moderate = fct_relevel(alcoholc_moderate, "nondrinker", "1-28g/d"),
                table1_alcoholc_heavy_vs_moderate = factor(alcoholc_heavy_vs_moderate, exclude = NA, levels = c("1-28g/d", ">28g/d", "P-value")),
                alcoholc_heavy_vs_moderate = fct_relevel(alcoholc_heavy_vs_moderate, "1-28g/d", ">28g/d"),
                table1_hrt_ref_pm = factor(hrt_ref_pm, exclude = NA, levels = c("No", "Yes", "P-value")),
                hrt_ref_pm = fct_relevel(hrt_ref_pm, "No", "Yes"),
                table1_eo_ref_pm_gxe = factor(eo_ref_pm_gxe, exclude = NA, levels = c("No", "Yes", "P-value")),
                eo_ref_pm_gxe = fct_relevel(eo_ref_pm_gxe, "No", "Yes"),
                table1_ep_ref_pm_gxe = factor(ep_ref_pm_gxe, exclude = NA, levels = c("No", "Yes", "P-value")),
                ep_ref_pm_gxe = fct_relevel(ep_ref_pm_gxe, "No", "Yes"),
                table1_diab = factor(diab, exclude = NA, levels = c("No", "Yes", "P-value")),
                diab = fct_relevel(diab, "No", "Yes"),
                table1_smk_ever = factor(smk_ever, exclude = NA, levels = c("No", "Yes", "P-value")),
                smk_ever = fct_relevel(smk_ever, "No", "Yes"),
                table1_fiberqc2 = factor(fiberqc2, exclude = NA, levels = c("1", "2", "3", "4", "P-value")),
                fiberqc2 = fct_relevel(fiberqc2, "1", "2", "3", "4"),
                table1_fruitqc2 = factor(fruitqc2, exclude = NA, levels = c("1", "2", "3", "4", "P-value")),
                fruitqc2 = fct_relevel(fruitqc2, "1", "2", "3", "4"), 
                table1_vegetableqc2 = factor(vegetableqc2, exclude = NA, levels = c("1", "2", "3", "4", "P-value")),
                vegetableqc2 = fct_relevel(vegetableqc2, "1", "2", "3", "4"),
                table1_redmeatqc2 = factor(redmeatqc2, exclude = NA, levels = c("1", "2", "3", "4", "P-value")),
                redmeatqc2 = fct_relevel(redmeatqc2, "1", "2", "3", "4"),
                table1_procmeatqc2 = factor(procmeatqc2, exclude = NA, levels = c("1", "2", "3", "4", "P-value")),
                procmeatqc2 = fct_relevel(procmeatqc2, "1", "2", "3", "4"))

label(gxe_table1$age_ref_imp) <- "Age"
label(gxe_table1$alcoholc) <- "Alcohol Intake"
label(gxe_table1$asp_ref) <- "Reg Aspirin/NSAID use"
label(gxe_table1$bmi) <- "BMI"
label(gxe_table1$calcium_totqc2) <- "Total Calcium Intake"
label(gxe_table1$diab) <- "T2D (ever diagnosed)"
label(gxe_table1$educ) <- "Education (highest completed)"
label(gxe_table1$famhx1) <- "Family History of CRC"
label(gxe_table1$fiberqc2) <- "Total Fiber Intake"
label(gxe_table1$folate_totqc2) <- "Total Folate Intake"
label(gxe_table1$fruitqc2) <- "Total Fruit Intake"
label(gxe_table1$heightcm) <- "Height"
units(gxe_table1$heightcm) <- "cm"
label(gxe_table1$hrt_ref_pm) <- "Any Post-Menopausal HRT Use"
label(gxe_table1$outcome) <- "Outcome"
label(gxe_table1$procmeatqc2) <- "Total Processed Meat Intake"
label(gxe_table1$redmeatqc2) <- "Total Red Meat Intake"
label(gxe_table1$sex) <- "Sex"
label(gxe_table1$smoke) <- "Smoking Status"
label(gxe_table1$smk_ever) <- "Smoking, never/ever"
label(gxe_table1$vegetableqc2) <- "Total Vegetable Intake"

# data for ggplots
# also includes variables for counts table
gxe_ggplot <- figi_gwas %>% 
  filter(gxe == 1, EUR_subset == 1) %>% 
  mutate(asp_ref = fct_explicit_na(asp_ref, na_level = "NA"), 
         asp_ref = fct_relevel(asp_ref, "NA", "Yes", "No"),
         asp_ref_count = fct_relevel(asp_ref, "No", "Yes", "NA"),
         aspirin = fct_explicit_na(aspirin, na_level = "NA"), 
         aspirin = fct_relevel(aspirin, "NA", "Yes", "No"),
         aspirin_count = fct_relevel(aspirin, "No", "Yes", "NA"),
         nsaids = fct_explicit_na(nsaids, na_level = "NA"), 
         nsaids = fct_relevel(nsaids, "NA", "Yes", "No"),
         nsaids_count = fct_relevel(nsaids, "No", "Yes", "NA"),
         folate_totqc2 = fct_explicit_na(folate_totqc2, na_level = "NA"), 
         folate_totqc2 = fct_relevel(folate_totqc2, "NA", "1", "2", "3", "4"),
         folate_totqc2_count = fct_relevel(folate_totqc2, "1", "2", "3", "4", "NA"),
         folate_dietqc2 = fct_explicit_na(folate_dietqc2, na_level = "NA"), 
         folate_dietqc2 = fct_relevel(folate_dietqc2, "NA", "1", "2", "3", "4"),
         folate_dietqc2_count = fct_relevel(folate_dietqc2, "1", "2", "3", "4", "NA"),
         alcoholc_heavy = fct_explicit_na(alcoholc_heavy, na_level = "NA"), 
         alcoholc_heavy = fct_relevel(alcoholc_heavy, "NA", ">28g/d", "nondrinker"),
         alcoholc_heavy_count = fct_relevel(alcoholc_heavy, "nondrinker", ">28g/d", "NA"),
         alcoholc_moderate = fct_explicit_na(alcoholc_moderate, na_level = "NA"), 
         alcoholc_moderate = fct_relevel(alcoholc_moderate, "NA", "1-28g/d", "nondrinker"),
         alcoholc_moderate_count = fct_relevel(alcoholc_moderate, "nondrinker", "1-28g/d", "NA"),
         alcoholc_heavy_vs_moderate = fct_explicit_na(alcoholc_heavy_vs_moderate, na_level = "NA"), 
         alcoholc_heavy_vs_moderate = fct_relevel(alcoholc_heavy_vs_moderate, "NA", ">28g/d", "1-28g/d"),
         alcoholc_heavy_vs_moderate_count = fct_relevel(alcoholc_heavy_vs_moderate, "1-28g/d", ">28g/d", "NA"),
         hrt_ref_pm = fct_explicit_na(hrt_ref_pm, na_level = "NA"), 
         hrt_ref_pm = fct_relevel(hrt_ref_pm, "NA", "Yes", "No"),
         hrt_ref_pm_count = fct_relevel(hrt_ref_pm, "No", "Yes", "NA"),
         eo_ref_pm_gxe = fct_explicit_na(eo_ref_pm_gxe, na_level = "NA"), 
         eo_ref_pm_gxe = fct_relevel(eo_ref_pm_gxe, "NA", "Yes", "No"),
         eo_ref_pm_gxe_count = fct_relevel(eo_ref_pm_gxe, "No", "Yes", "NA"),
         ep_ref_pm_gxe = fct_explicit_na(ep_ref_pm_gxe, na_level = "NA"), 
         ep_ref_pm_gxe = fct_relevel(ep_ref_pm_gxe, "NA", "Yes", "No"),
         ep_ref_pm_gxe_count = fct_relevel(ep_ref_pm_gxe, "No", "Yes", "NA"),
         diab = fct_explicit_na(diab, na_level = "NA"), 
         diab = fct_relevel(diab, "NA", "Yes", "No"),
         diab_count = fct_relevel(diab, "No", "Yes", "NA"),
         smk_ever = fct_explicit_na(smk_ever, na_level = "NA"), 
         smk_ever = fct_relevel(smk_ever, "NA", "Yes", "No"),
         smk_ever_count = fct_relevel(smk_ever, "No", "Yes", "NA"),
         fiberqc2 = fct_explicit_na(fiberqc2, na_level = "NA"), 
         fiberqc2 = fct_relevel(fiberqc2, "NA", "1", "2", "3", "4"),
         fiberqc2_count = fct_relevel(fiberqc2, "1", "2", "3", "4", "NA"),
         fruitqc2 = fct_explicit_na(fruitqc2, na_level = "NA"), 
         fruitqc2 = fct_relevel(fruitqc2, "NA", "1", "2", "3", "4"),
         fruitqc2_count = fct_relevel(fruitqc2, "1", "2", "3", "4", "NA"),
         vegetableqc2 = fct_explicit_na(vegetableqc2, na_level = "NA"), 
         vegetableqc2 = fct_relevel(vegetableqc2, "NA", "1", "2", "3", "4"),
         vegetableqc2_count = fct_relevel(vegetableqc2, "1", "2", "3", "4", "NA"),
         redmeatqc2 = fct_explicit_na(redmeatqc2, na_level = "NA"), 
         redmeatqc2 = fct_relevel(redmeatqc2, "NA", "1", "2", "3", "4"),
         redmeatqc2_count = fct_relevel(redmeatqc2, "1", "2", "3", "4", "NA"),
         procmeatqc2 = fct_explicit_na(procmeatqc2, na_level = "NA"), 
         procmeatqc2 = fct_relevel(procmeatqc2, "NA", "1", "2", "3", "4"),
         procmeatqc2_count = fct_relevel(procmeatqc2, "1", "2", "3", "4", "NA"))

gxe_ggplot_subset <- gxe_ggplot %>% 
  filter(vcfid %in% exposure_subset)
```



## Additional Analyses ``r params$exposure`` {.tabset}
```{r child = paste0('results_report_child_additional_analysis_', params$exposure, '.Rmd')}
```

