---
title: "CRC - Alcohol Literature Review"
bibliography: /Users/mak/Dropbox/library.bib
output: 
  #pdf_document:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    theme: "cosmo"
---


<style type="text/css">
h1 { /* Header 1 */
  font-size: 22px;
  font-weight: bold;
}
h2 { /* Header 2 */
    font-size: 20px;
    font-weight: bold;
}
h3 { /* Header 2 */
    font-size: 18px;
    text-decoration: underline;
}
hr {
  border: 1px solid #000;
}
blockquote p {
  font-size: 12px;
}
</style>

<!-- #############################  -->

# Epidemiology, Reviews


# Methods and Results

(make this section study focused)

### @Slattery2001
- Pop: Kaiser, Utah, Minnesota
- E: alcohol based on recall 10 and 20 years back. None/Intermediate/High (cutpoints specific to alcohol type)
- MSI: defined with panel of 10 tetranucleotide repeats
- Stats: technically, outcome is probability of having MSI+ tumors vs nonMSI (MSS), compared to controls. Interested in risk of MSI+ tumors as a result of diet, alcohol. 
- Results: alcohol increased risk of MSI+ tumors. is the case for specific types too (only liquor significant). Sig interaction with Smoking (high alcohol + high smoking = you're screwed with MSI+)

### @Satia2005
- Pop: North Carolina, 875 NHW, 659 AA
- E: Dichotomous No/Yes, based on ref period (1 year prior dx/selection)
- MSI: 5 commonly used markers
- Stats: MSI-H, MSI-L/MSS, vs control. also MSI-H vs MSI-L/MSS
- Results: betas more elevated for MSI-H vs controls than the other tumor types, but nothing significant for alcohol. Results were mostly not compelling (red meat was suggestive)


# Mechanisms  

(make this section findings focused)

- alcohol and MSI+ tumors: alcohol could influence mucosal cell proliferation and related histological changes. mucosal hyper-regeneration? Slattery found interaction with smoking, no further discussion on why. Take away point - weaker associations between alcohol and CRC could be because not account for tumor types e.g. MSI status (you should still read as many of those papers as possible..) [@Slattery2001]




### FYI
- red meat and MSI-H tumors: HCAs and adduct formation. Heme - cytotoxic and proliferative effects on colonic cells [@Satia2005]

<br><br><br><br><br><br><br><br><br><br><br><br>






# Bibliography