---
title: "CRC - NSAID Literature Review"
bibliography: /Users/mak/Dropbox/library.bib
output: 
  #pdf_document:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    theme: "cosmo"
---

# Riki email

Post Harmonization Process

Investigate the distribution of the Es across studies
Check this for each study and study set (when study is included multiple times check if distribution of Es is similar across sets as well)
Are there outliers first check the study design, for instance is it a study in smokers or a trial for a specific E and the way the E was assessed by looking at what question(s) were used by checking the mapping document and/or used questionnaire (available on the portal)
Are the overall values within the normal range?
What will you do with outlier? Reassign a logical maximum, exclude?
If there is no explanation please check with Yi Lin
Discuss and evaluate the best approach to code the existing variables
Explore which coding schema of the E variable provides the least heterogeneity (I2 and p for heterog.), strongest (effect size) and most significant (p-value)
Please note that we cannot go back to studies for harmonization of additional variables given available resources and the very large number of studies involved.
Investigate distribution by known/well established effect modifiers (eg sex is usual, could be others like alcohol and folate)
Check for heterogeneity of the effect
Evaluate if any factors, such as study design, sex, year of enrollment, country/continent, … can explain some or all of the heterogeneity

 
# Epidemiology and Mechanisms


# Methods

## Genotyping and Imputation
- In brief, genotyped SNPs were excluded based on call rate (<98%), lack of Hardy-Weinberg equilibrium (HWE) in controls (P <1×10−4), and minor allele frequency (MAF) (MAF <5% for WHI Set 1, Diet, Activity and Lifestyle Study [DALS] Set 1, and Ontario Familial Colorectal Cancer Registry [OFCCR]; MAF <5/No. of samples for each other study) [@Nan2015a]


## Analysis of imputed markers
- reference for using dosage (one of several): Jiao S, Hsu L, Hutter CM, Peters U. The use of imputed values in the meta-analysis of genome-wide association studies. Genet Epidemiol. 2011;35(7):597-605



# Literature

## @Nan2015a
- Intro
- Methods
- Results
- Discussion

# Mechanisms  

# Bibliography